### PR TITLE
Added The Logo

### PR DESCRIPTION
**Pull request by sebnitu**
Hey,

I've added the logo and textures in index.html. This is my first fork and pull request so I hope I'm doing this right :D

Thanks!

### CODE REVIEW

**Comment by sebnitu** [comment]
Oh, and I have the images hosted on my site. Let me know if you want them somewhere else. I didn't want to include the images in the project files themselves but if you prefer to do that, up to you :)

**Comment by OscarGodson** [comment]
SWEET! Thanks!

Yeah, could you include those directly?

Also, checkout the `0.1.0-build-refactor` branch and how we do it there. Just overwrite the images and do your styles in that branch and then send a pull request there since it's our WIP. :)

You'll need to modify the `/docs` files, NOT `index.html` in that branch because we've moved to generating the docs from the README. the `/docs` directory has like the header and footer tho which is what you changed.

**Comment by johnmdonahue** [comment]
Hey @sebnitu. Looking sweet! We're currently working on the docs on [0.1.0-build-refactor](https://github.com/OscarGodson/EpicEditor/tree/0.1.0-build-refactor) and I just made some updates on the styles here: [doc-style-tweak](https://github.com/OscarGodson/EpicEditor/tree/doc-style-tweak). It'd be awesome if you could work from that point and work your styles magic there.

The new build system generates the `index.html` from the `README.md` and a header/footer found in `/docs` so moving forward we will not be editing the `index` file directly. This is to prevent needing to update documentation on both the README and index.

To build the docs you will need to have node installed as well as `marked` and `jake`. You can check the [wiki](https://github.com/OscarGodson/EpicEditor/wiki/Contributing) for more on this or feel free to hit me up if you have any questions on this or how to handle checking out/targeting branches outside of master. I am happy to work directly with you on this. You can get a one-click install of NodeJS [here](http://nodejs.org/). Once you have Node installed just run the commands below and you should be all set:

``` bash
$ sudo npm install -g jake foounit jshint uglify-js marked
```

Thanks!

PS: What OS are you on Windows/Linux/Mac?

**Comment by OscarGodson** [comment]
@sebnitu yeah... what @johnmdonahue said ;) (and he's on a Mac)

**Comment by sebnitu** [comment]
Yup, I'm on a Mac.

That all sounds great! I'm going to get this taken care of after work today. I'll let you know if I run into any issues trying to figure this stuff out. Thanks for all the detailed info/directions. A lot of this stuff is new to me but I'm excited to dive in and learn :D

Thanks guys!

**Comment by OscarGodson** [comment]
@sebnitu this will be a great test to see how easy it is. Feel free to update the wiki page about [contributing to EpicEditor](https://github.com/OscarGodson/EpicEditor/wiki/Contributing) if something is incorrect or not explained enough.

We want it easy enough for anyone who doesn't know node to simply edit the code and build it (`jake build` builds the code `jake docs` builds the docs)

**Comment by johnmdonahue** [comment]
@OscarGodson yes! Very much so. That said, it would be awesome if we could try out the [refactored Jakefile](https://github.com/OscarGodson/EpicEditor/pull/91) for this (why I was asking on the OS). Will you have any time to check that out and maybe merge before @sebnitu gets started? I can pull any 0.1.0-build-refactor merges to the doc-style-tweak branch as well so we can just work from that branch if that makes sense?

**Comment by OscarGodson** [comment]
@johnmdonahue you should just merge it in if you feel safe about it. I trust ya. I just commented on the pull request also. It's just dev stuff anyways and @sebnitu can let you know if there's issues with it.

**Comment by OscarGodson** [comment]
Oh, gonna close this one, @sebnitu just because it's gonna be sent to the other branch anyway and it'll need updating based on the build stuff.

**Comment by johnmdonahue** [comment]
@sebnitu I merged the new Jakefile build process and style tweaks I mentioned into the `0.1.0-build-refactor` branch. You should be all set to just work straight from there and ignore the other branches.

Let me know if you have any questions at all. And thanks again!

@OscarGodson - Let me know if you want me to "trim" any unused or merged branches to clean things up a bit?

**Comment by johnmdonahue** [comment]
@sebnitu One key thing I forgot to mention is that `index.html` changes should take place on the following 3 files only:

```
README.md
docs/header.html
docs/footer.html
```

To see changes made to those files in a browser, simply rebuild `index.html` by running:

``` bash
$ jake docs
```

If you wanted to extract the `css` and `js` to something like `docs/main.js` or whatever, that would eliminate the build step for simple js/css tweaks - only requiring a new build when the html changes.

@OscarGodson any thoughts on that idea?

**Comment by OscarGodson** [comment]
@johnmdonahue yes. Totally. Ive been meaning to remove the unused branches. 0.1.0-wip, 0.1.0, and shortcuts were mine so you can remove those. `feature/crud` can be removed once you give me the OK as well.

I'd like to remove the CSS and JS at some point. Feel free to do it if you're on a roll ;) Less building the better. I'm actually gonna work on implementing `watch()` in Jake this weekend so builds are [can be] automatic!

**Comment by johnmdonahue** [comment]
@sebnitu I just pushed a few changes to `0.1.0-build-refactor`. The styles and js are now extracted to `docs/css` and `docs/js`. This should hopefully make development a bit smoother on the docs. No rebuild required unless one of the following are modified: `docs/header.html`, `docs/footer.html` or `README.md`.

Let me know if you need any help on this. :D

**Pull request closed without merging**
