### PR TITLE
Added support for bower

### PR DESCRIPTION
**Pull request by brunowego**
For better integration with bower is necessary this file.

### CODE REVIEW

**Comment by brunowego** [comment]
If merge, make a new tag. Thanks.

**Comment by mrhanlon** [comment]
Thanks for this, +1. I was about to propose the same.

**Comment by mrhanlon** [comment]
Looking at your bower.json, on line 10 there is an extra trailing comma that is invalid. Also, EpicEditor doesn't actually depend on jQuery, only the docs example does. I recommend to remove it from the dependencies.

**Comment by zackyang000** [comment]
+1

**Comment by brunowego** [comment]
Yes @mrhanlon, fixed now! Thanks!

**Comment by brunowego** [comment]
Waiting for merge!

**Comment by OscarGodson** [comment]
EpicEditor doesn't require jQuery. I'm going to go ahead and give you access to merge this yourself @brunobatista. I've never used Bower so I wouldn't even know if this is correct or not. But, jQuery is not a dep of EpicEditor so I would assume that could be removed.

**Comment by brunowego** [comment]
New pull in #348

**Pull request closed without merging**
