### PR TITLE
Ticket #27 - simple ios scrolling fix

### PR DESCRIPTION
**Pull request by Gankra**
Oh man this is so much better. Doesn't change anything important. Just adds some extra css to the wrapper iframe.

Also doesn't have _any_ of the stupid issues I was having before. Seems to work great, and doesn't effect anything else as far as I can tell.

### CODE REVIEW

**Comment by OscarGodson** [comment]
haha. I actually didn't have multiple iframes before because it was going to be a pain. I ended up adding it because of the growing number of bugs between preview, base, and editor. I'm glad it worked out this time :)

Are these styles things that _need_ to be there for iOS tho? If so you should probably set them in the JS because these are supposed to be themes and therefore easy to modify without having it totally break or lose support for mobile.

**Comment by Gankra** [comment]
Alright, good call. I've also noticed this line here: https://github.com/OscarGodson/EpicEditor/blob/develop/src/editor.js#L615

sets the height of the body on the outer-most iframe, but nothing ever seems to update it. This was fine before since the iframe was basically exploding out of the wrapper div (go ahead, inspect element, it has a computed height of "0px"!). However, now that I'm making the wrapper div actually constrict the bounds of the iframe, the fact that the body has a fixed height seems to be breaking reflow. 

It seems like setting height:100% on this line instead seems to work fine. Any thoughts on this?

**Comment by OscarGodson** [comment]
> sets the height of the body on the outer-most iframe, but nothing ever seems to update it. 

It never needed to be updated if I recall correctly because the only time it changed was on fullscreen open/close which it is updated then.

Just make sure it works fine in firefox, especially and opening/closing fullscreen in native and non-native fullscreen works as expected.

**Comment by Gankra** [comment]
Made the change, and everything seems to work right in firefox and all the other browsers I've tried.

**Comment by OscarGodson** [comment]
Cool, i'll check it out tomorrow. Really busy tonight but should be able to tomorrow. Do you want it in this next minor release or should we hold off for 0.3.0?

**Comment by Gankra** [comment]
Whichever you prefer. I merge my stuff into my own build as it gets okayed, so all that matters to me is that it's production quality. :)

**Comment by Gankra** [comment]
Got my hands on an ipad, and it's not cooperating much. I'm thinking just letting the bloody thing autogrow on ios might just be the right thing.

**Comment by OscarGodson** [comment]
So, what do you wanna do with this PR? Should I review this? I don't have an iPhone so, I'll test it in desktop Safari just to make sure there are no regressions, but I'll take your word if it works well and you wanna merge it :)

**Comment by Gankra** [comment]
So after much work and testing, I'm leaning to the conclusion that inner scrolling areas is just _not_ mobile friendly. It's hard to browse, there's no indication that it _does_ scroll, and the platform is fairly bad at identifying what level of scroll you want to be interacting with. Therefore the only way to make the system ios (or android/wp/etc) friendly is to just enable autogrow (at least on that platform). Obviously autogrowing elements could break user layouts, so I'm inclined to just officially say "if you want to be mobile friendly, you should set autogrow:true", but keep autogrow:false as the default.

Currently hacking on the autogrow functionality.

**Comment by Gankra** [comment]
So basically, I'm inclined to kill this PR at this point, but am willing to leave it up at the moment to hedge my bets.

**Comment by OscarGodson** [comment]
@Gankro Feel free to merge this if you want. Since you're iffy on it I'll leave it up to you. It's a small change, so whatever you want. :)

**Pull request closed without merging**
