### PR TITLE
Ticket #268 - potential fix to whitespace issues

### PR DESCRIPTION
**Pull request by Gankra**
Here's the proposed fix. I've tested against all our target browsers (personal eyeball tests and unit tests), and have it staged for production in my deployment as a hotfix.

I will not be writing unit tests, as I'm currently a bit busy, but I have posted recommendations for unit tests you may want to write in #268, should you want to start testing this behaviour.

### CODE REVIEW

**Comment by Gankra** [comment]
What are the odds of getting this merged and released by wednesday? Evidently we're under a bit more pressure than I thought to ship _something_ for demo purposes. No one here wants to ship a tweaked fork of a third-party lib, and this is a pretty major bug if it's repro-ing on other machines.

**Comment by OscarGodson** [comment]
Yeah, I was able to repro it too. I'm at OSCON today. I'll test it at lunch!

**Comment by OscarGodson** [comment]
@Gankro If anything, this makes everything simpler and works more consistently across browsers. There's one odd thing in IE9 and 10 tho. Clear localstorage and start fresh. Type some text (notice the big gap above the text). Now refresh. Text moves closer to top of editor.

**Comment by OscarGodson** [comment]
Oh, and this is merged by the way

**Comment by Gankra** [comment]
Yeah that seems to be a thing with how IE treats divs vs brs. I think it does new lines with divs by default, whereas we use brs.

**Pull request merged**
