### PR TITLE
Makefile Build and JSHint Refactor

### PR DESCRIPTION
**Pull request by johnmdonahue**
Before going too far into the tests/API update, I thought I'd give this a whirl. This works with the existing API and should be useful down the line for handling versioning and creating easy to download zips (`epiceditor.zip`).

Currently the JSHint config is pretty strict but, with the exception of whitespace and some `===`, it seemed to fall in line with the existing code style. I figured its easier to loosen the requirements starting from a stricter point than vice versa, so if the it's too opinionated for your tastes it should just be matter of toggling a few things off (whitespace, eqnull come to mind).

The Makefile relies on JSHint and UglifyJS for minification. Both of these are simple installs from npm, but let me know if a NodeJS/npm requirement is an issue here. Also there are some notes in the Makefile concerning linting of the fullscreen and showdown modules - I was thinking it might make sense to pull in your `EpicEditor-Flavored-Markdown` as a git-submodule.

For reference: the existing build of epiceditor.js weighs in at 37K and the new build creates an unminified 40K file and minified of 23K. 

I'm open to any modifications, suggestions, or cherry-picking here. Unfortunately, I won't have a lot of time to jump back on it until next week.

Let me know your thoughts.

PS: This pull request written using the current build. ;)

### CODE REVIEW

**Comment by OscarGodson** [comment]
rad! I'll clone this tonight and check it out! You rock.

**Comment by techwraith** [comment]
Any chance we could port that makefile over to Jake? Scotch uses Geddy, which uses Jake by default for build steps and I'd like to integrate EE into scotch as pain free as possible.

**Comment by johnmdonahue** [comment]
I actually started one. But what took me 20 min for a Makefile cost a couple hours trying to accomplish the same with Jake so I abandoned it. I have no preference on the build tool and since it's already heavily reliant on Node, Jake is a trivial addition. 

It's probably a simple task for someone more experienced with Jake/Node but here's what I had - complete with EpicASCII&trade; ;)

https://gist.github.com/1996846

**Comment by techwraith** [comment]
@johnmdonahue Like! I might give this one a shot.

**Comment by OscarGodson** [comment]
@johnmdonahue Yeah, if possible I'd like to use Jake too because I'm used to it (i use it all day at work) and I can get in person help from @mde ;)

But I like how you've separated and good idea on making EE flavored markdown a submodule. I'd like to dynamically build that in each time so when I make a change I dont have to manually go to closure-compiler.appspot and copy, paste, then copy, paste again, commit and push.

Also, for the EE minified we can compress that copyright stuff down 99% by just including it on a separate page like jQuery does: jquery.org/license or include it in the repo as a separate file.

**Comment by johnmdonahue** [comment]
Cool. Yeah I was stoked on the Jakefile route until I just ran out of time for it, so anyone else's expertise here would be awesome. I'd love to learn a thing or two.

I made TODO notes in the Makefile for most of what you mentioned otherwise. Ideally we could just pull in the EEMD submodule as part of the build process. That's where I was headed with it anyway.

As for the copyright stuff, I'm not too legal savvy so I was trying to err on the side of too much. The comment chunk in Showdown is huge and I didn't know what absolutely had to stay in. UglifyJS by default (w/o `-nc`) will keep comments that begin a file so I kinda hacked around this by throwing a `!{}` in the mix. I can attempt to replicate jQuery style but I'd probs need some guidance to make sure I get it right.

Another nice thing to add here would be versioning both for the EE core and EEMD submodule. Not sure how far Node/module pattern you guys want to take this, but these 2 libs might make good candidates for npm packages which would make them available to other builders like [Ender](https://github.com/ender-js/Ender) and maybe encourage plugin-style mashups with Bootstrap etc.

**Comment by OscarGodson** [comment]
For the copyright I'll modify showdown.js and the others if I can tonight so we can, to be safe, keep it but just shorten it.

For versioning I was just going to use git tags and the standard 0.0.0. I was going to start the tagging in 0.1.0 which would be the first official beta. I haven't written any NPM stuff but @Techwraith could chime in on if my format would work or not.

If you still have just a tad bit of time, do you wanna send another pull request with your change to options() and it bein in the constructor? Figured it's be an easy pull request and it'd be good to split it up from the massive testing and jakefile stuff. If like to get that change an you to get credit :)

Also, @techwraith were gonna try porting the makefile to a jakefile or should I try jumping on it? I cant really get to this pull request until I at least finish fullscreen in FF and IE because it's te only real major hole in EE right now.

**Comment by techwraith** [comment]
I'm not going to have time for a while, sorry dude. Go for it though ;)

**Comment by OscarGodson** [comment]
Sorry for the typos. On an iPhone, clicked submit and I can't edit the response :(

I meant to say, "id like you to get credit"

**Comment by johnmdonahue** [comment]
>  Figured it's be an easy pull request and it'd be good to split it up from the massive testing and jakefile stuff

@OscarGodson, are you asking for a stand-alone `opts` API update based on your current master? Or this restructured branch/style? I am guessing you are asking for me to just finish that part separate from the tests that were originally attached? Update `README`, `index` and wiki as well?

I have a little time tonight to try to hammer some things out. I'll wait for clarification but I'll try to get a request in on the `opts` change at least and if I'm feeling frisky maybe tinker with the [Jakefile](https://gist.github.com/1996846) I started.

**Comment by OscarGodson** [comment]
Yes exactly. Basically a rework of the API with the options in the constructor and the auto EE init based on the ID, change the index file docs and example-1 to work with the new API as well as the README. If you can't get to the docs thats fine too. I can merge your request into a develop branch or something.

**Comment by johnmdonahue** [comment]
See: [#58](https://github.com/OscarGodson/EpicEditor/pull/58)

**Pull request closed without merging**
