### PR TITLE
Issue #259 - Embed images in CSS so asset fingerprinting works.

### PR DESCRIPTION
**Pull request by pbougie**
Moves images into base64-encoded CSS to fix problems when using the Rails asset pipeline and asset fingerprinting. Changing an image is almost as easy as it was: instead of changing the image in the filesystem, you simply base64 encode it and paste it into the CSS. Use an encoder such as this one: http://webcodertools.com/imagetobase64converter

### CODE REVIEW

**Comment by OscarGodson** [comment]
@Gankro what do you think about this?

**Comment by Gankra** [comment]
Base64 embedding in CSS:
- more portable
- easy for users to clobber/replace
- less HTTP reqs
- well supported as far as I can tell
- better versionable?

Seems like a good call to me. My only issues are implementation specific.

**Comment by pbougie** [comment]
> Since this is all in an iframe, its not clear to me that you need anything more than .epiceditor-fullscreen-foo as the selectors here.

I never touched any of the selectors. Any refactoring of selectors should probably be done elsewhere.

> Semantically, should these not be <button>?

Agreed. I made the changes.

> Not a huge fan of useless whitespace edits, but that's just me.

I mistakenly let those go through. I've reverted the whitespace edits. However, trailing whitespace should be removed project-wide but should be done in another commit.

**Comment by OscarGodson** [comment]
@pbougie thanks. I'll take a look at this tonight or something. Did you check IE9-10?

**Comment by pbougie** [comment]
Works well in IE9-10. Is there somewhere where you list browser compatibility for EpicEditor?

**Comment by OscarGodson** [comment]
Thanks @Gankro! The code all looks good to me too. I'm going to test it locally real quick then merge it if it looks good.

**Comment by OscarGodson** [comment]
IE9: 
screen shot 2013-07-06 at 1 11 24 pm

**Comment by OscarGodson** [comment]
Buttons are still buttons and base64 doesnt seem to be working.

**Comment by pbougie** [comment]
@OscarGodson Works fine here. Looks like the new styles are missing. Did you force reload the CSS?

**Comment by OscarGodson** [comment]
I can try again later. Works fine in IE10 mode tho which means the caching shouldn't be a problem.

**Comment by OscarGodson** [comment]
@pbougie Deleted everything (cookies, cache, etc) and finally it worked. Hopefully this isn't an issue when upgrading for people. 

Thanks again for the contribution :)

**Pull request merged**
