### PR TITLE
CRUD and new file schema

### PR DESCRIPTION
**Pull request by OscarGodson**
What do you guys think? Added full CRUD event support and a new file schema. Also, of course, added tests.

It'd be nice if you guys could run through it and make sure I'm not missing anything.

### CODE REVIEW

**Comment by OscarGodson** [comment]
@johnmdonahue Remember to remove your localStorage contents after checking out that branch since the schema is totally different and it'll just crash.

**Comment by johnmdonahue** [comment]
Ha! Will do.

**Comment by johnmdonahue** [comment]
@OscarGodson This is looking good on my end. I haven't run into any errors or major issues so far.

### A few notes:
1. I saw this todo referring to the `instanceId` and it makes sense to me, should we go ahead and implement? `// TODO: Put underscore to denote that this is private`
2. It may help performance a bit to clear save intervals on `unload` and any other situation where the editor is removed either programmatically or accidentally. I'm guessing this has something to do with the next note.
3.  Seems like the test suite is slowing down significantly with the added 10. Safari handles it like a boss but FF and Chrome are choking. Maybe we should remove the editors entirely after they are no longer needed (a lot of iframes and intervals for one page). Below is a breakdown of before (`0.1.0-build-refactor`) and after output on Chrome, FF, and Safari with the avg time for `feature/crud` in parens.

```
Safari (10-15 seconds)
>> foounit summary: 0 failed, 55 passed, 0 pending, 55 total
>> foounit runtime: 11972ms

>> foounit summary: 0 failed, 65 passed, 0 pending, 65 total
>> foounit runtime: 10030ms

Firefox (30-60 seconds)
>> foounit summary: 0 failed, 55 passed, 0 pending, 55 total
>> foounit runtime: 10592ms

>> foounit summary: 0 failed, 65 passed, 0 pending, 65 total
>> foounit runtime: 41144ms

Chrome (1-2 minutes)
>> foounit summary: 0 failed, 55 passed, 0 pending, 55 total
>> foounit runtime: 18244ms

>> foounit summary: 0 failed, 65 passed, 0 pending, 65 total
>> foounit runtime: 128427ms
```

Thanks.

**Comment by OscarGodson** [comment]
Yikes that seems strange and wrong. I'm getting in Chrome:

```
>> foounit summary: 0 failed, 65 passed, 0 pending, 65 total
>> foounit runtime: 8781ms
```

I'd never test if it took that long. Yeah, we should clean up save intervals, but I think there might be something else wrong, but I have no idea what. I can't repro those speeds locally at all. :\

And yeah, it's safe to put the underscore.

**Comment by OscarGodson** [comment]
One quick thing you could do to see if it works is add `autoSave:false` to all the test setups and see if it runs faster. That will completely skip over the interval stuff.

**Comment by johnmdonahue** [comment]
You're getting 8.7 seconds on Chrome for the `feature/crud` build? Wow! For the record those times were with inspector closed and on a fresh restart of Chrome and a brand new install of FF.

I really think it has something to do with the number of iframes and simultaneous intervals running. It really stacks up fast. Checkout the DOM / timeline in inspector.

**Comment by OscarGodson** [comment]
@techwraith just ran it and it got 10.1 seconds his first run through. One thing I noticed is that timeline the more times I test with the timeline view on the longer it takes. First run with the timeline turned on it took 20 seconds and then longer the next, etc.

**Comment by johnmdonahue** [comment]
Weird! Are you saying even if you turn off timeline/profiling/inspector after using them once? The numbers I got are with inspector/timeline off/closed. Either way, does it make sense to you to just remove the elements when they are no longer needed and destroy intervals? 

Not that anyone's checking but my guess is that IE6 would explode with those tests. Anything over 5-10 iframes on a page and it shits. The test suite now has probably more than 40 iframes with 2 more embedded in each. That's a lot of doms. :D

**Comment by OscarGodson** [comment]
Yeah, re-ran after I closed the timeline and got 8.6 seconds.

Destroying the elements is done in EE already in `unload()`. Intervals are not. Maybe add timer removal in `unload()` to this branch and see if you can get faster times. Add the `unload()`s in the `after()` methods of foounit and you should be good and hopefully faster for you? This would probably work fine:

``` js
after(function(){
  editor.unload();
});
```

IE6 probably wouldnt even run the tests since localStorage is used :P

P.S. Do you have any weird extensions or anything turned on?

**Comment by johnmdonahue** [comment]
No extensions. I made a quick attempt to add `autoSave:false` and the `after` function but it'll take a bit more tweaking than that and I don't really have the time to look into it ATM. This pull isn't really about the tests anyway so maybe we can backburner that.

**Comment by OscarGodson** [comment]
I'll merge it in then now

**Comment by OscarGodson** [comment]
NVM, can't. Merge conflicts galore after pulling. Will fix tonight then push.

**Pull request merged**
