### PR TITLE
added the ability to wrap a textarea

### PR DESCRIPTION
**Pull request by bytespider**
Wrap a textarea with the container and use that as the sync textarea

### CODE REVIEW

**Comment by OscarGodson** [comment]
So, to be clear, if you had:

``` js
<div id="epiceditor">
  <textarea></textarea>
</div>
```

It would use that textarea, automatically, to sync content?

**Comment by bytespider** [comment]
That's the idea

**Comment by bytespider** [comment]
Removed check and IE10 tested

**Comment by OscarGodson** [comment]
Rad! I'll check play with this when I get home tonight then. Thanks, man!

**Comment by OscarGodson** [comment]
Pulled this down and it doesn't appear to work for me. 

``` html
  <div id="epiceditor">
    <textarea></textarea>
  </div>
  <script src="/epiceditor/js/epiceditor.js"></script>
  <script>
    var editor = new EpicEditor().load();
  </script>
```

The textarea appears to be removed. This line is doing it (99.9% sure)

https://github.com/OscarGodson/EpicEditor/blob/develop/src/editor.js#L532

Actually, I'm not sure how this worked for you since `self.element` is whatever you give it: https://github.com/OscarGodson/EpicEditor/blob/develop/src/editor.js#L375-L380 :P

**Comment by bytespider** [comment]
The loading from the contained textarea definatly works for me, however what I hadn't tested or checked was that the textarea is placed back on the form after the editor is done.

Think I might need to play with this a little before you consider pulling this.

**Comment by OscarGodson** [comment]
oh, I see. This was just for initial loading. Yeah, most people requested the textarea feature so that they could submit a form the old school way so the textarea has to be in the DOM when the form is submitted.

**Comment by bytespider** [comment]
What's your feelings on CSS added via JS? In this case,`'self.settings.textarea.style.display = 'none';`?

**Comment by OscarGodson** [comment]
As long as the docs make it clear that by putting the textarea in the epiceditor container will hide the textarea and replace it with epiceditor.

**Comment by bytespider** [comment]
I believe this is complete. Fancy giving it a go?

**Comment by OscarGodson** [comment]
Will do, sorry for the delay. I've been reviewing PRs for the 0.2.1 release. I'm going to package and ship 0.2.1 first and then I'll take a look at this. I will try to package and ship it tonight and take a look at this tomorrow. Thanks again!

**Comment by bytespider** [comment]
Ah, I thought perhaps you weren't sure I'd finihed making changes.
—

**Comment by OscarGodson** [comment]
OK, 0.2.1 was just released. I'll take a look at this ASAP (tonight/tomorrow) and test it in all the browsers.

**Comment by OscarGodson** [comment]
OK, checked and everything looks and works good. Few things:
1. Can you use `_applyAttrs`?
2. Can you do `typeof x` instead of `typeof(x)` as it fits more inline with the styles
3. Add docs (edit the README.md the file and then run `jake docs`)

If you don't have time or don't want to I can take care of these myself.

**Comment by OscarGodson** [comment]
P.S. sorry it took so long to get to this. Was busy with stuff :(

**Comment by OscarGodson** [comment]
bump?

**Comment by bytespider** [comment]
Yeah sorry, newborns can be a little distracting. I'll look into this weds/thurs as I'm back to work then
—

**Comment by OscarGodson** [comment]
@bytespider totally understood. Thanks :)

**Comment by OscarGodson** [comment]
I just noticed you put some commits in. Is that everything you wanted to get in?

**Comment by bytespider** [comment]
I think so, unless you had some comments on the docs?
—

**Comment by OscarGodson** [comment]
Rad, no, I just never got a comment from you. I don't get notified of commits, just comments :) I'll look at it during lunch

**Comment by bytespider** [comment]
Oh right, Thought it did as the commits were inline on GH
—

**Comment by OscarGodson** [comment]
When I mentioned applyAttrs, I didn't mean that one style, I meant where you set that block of attrs on L540-L543.

**Comment by bytespider** [comment]
Clearly I miss understood you. Will sort.
—

**Comment by bytespider** [comment]
Okay. So I used _applyAttrs, however it refuses to set frameborder. 
Therefore I updated _applyAttrs to use setAttribute instead.

**Comment by OscarGodson** [comment]
I will review this ASAP :) I wanna get this into the next release!

**Pull request merged**
