### PR TITLE
Styles update

### PR DESCRIPTION
**Pull request by sebnitu**
Ok, I hope I did this right. Please let me know. I had to create a new branch because I guess I wasn't working in one when I was making my updates. I'm just really confused lol >.<

### CODE REVIEW

**Comment by OscarGodson** [comment]
Whoo! looks great, man!

The issue was probably you needed to be in the 0.1.0-build-refactor branch and maybe you were in master? Also, make sure to pull _our_ 0.1.0-build-refactor before you start coding anything to see the updates to make your life easier later with merge conflicts and stuff (i noticed you pulled after). Either way, it's working on my end and seems to have the latest code and no conflicts so I think we're all good!

**Comment by OscarGodson** [comment]
Also, do you have this in your `~/.bash_profile`?

```
function parse_gb {
  cut -c17- .git/HEAD 2> /dev/null
}
PS1="\h:\[\033[01;36m\]\$(parse_gb) \[\033[00;38m\]\W$ "
```

That'll show you the current branch you're on if you're in a git repo. This will help with accidentally not being in the right branch ;)

**Comment by sebnitu** [comment]
I don't see a `.bash_profile` file. I see a `.bash_history` though :-/

Here's what my branches look like:

```
*(no branch)
master
stylesUpdate
remotes/origin/0.1.0
remotes/origin/0.1.0-build-refactor
remotes/origin/0.1.0-wip
remotes/origin/HEAD -> origin/master
remotes/origin/doc-style-tweak
remotes/origin/feature/crud
remotes/origin/gh-pages
remotes/origin/jakefile-cleanup
remotes/origin/master
remotes/origin/shortcuts
remotes/origin/stylesUpdate
remotes/upstream/0.1.0
remotes/upstream/0.1.0-build-refactor
remotes/upstream/0.1.0-wip
remotes/upstream/doc-style-tweak
remotes/upstream/feature/crud
remotes/upstream/gh-pages
remotes/upstream/jakefile-cleanup
remotes/upstream/master
remotes/upstream/shortcuts
```

And when I would checkout `remotes/origin/0.1.0-build-refactor` I got this message:

```
Note: checking out 'remotes/origin/0.1.0-build-refactor'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

git checkout -b new_branch_name

HEAD is now at 2559099... rebuild doc from readme update
```

Which downloaded the right files apparently but it didn't actually switch me to that branch.

Another thing I don't get is why I have pretty much dublicate branches at `remotes/origion/...` and `remotes/upstream/...`

I'm sure it was just a dumb mistake on my part but glad you didn't have issues on the merge :)

**Comment by OscarGodson** [comment]
Awh i see, you dont do `remotes/origin/...`. Just do `git checkout {branchname}`. Thats it. All that other stuff is the server's copies of the branches. I.e. if you delete one of those it'll be removed from github (sorta, but i wont go into details haha).

Next time you want to work on something you should simply do:

```
$ git checkout 0.1.0-build-refactor
$ git pull git@github.com:OscarGodson/EpicEditor 0.1.0-build-refactor
```

(note: you can shorten git@github.com:OscarGodson/EpicEditor by doing: `git remote add their git@github.com:OscarGodson/EpicEditor` like you do with `origin`)

and thats it :) when you're done changing stuff:

```
$ git commit -a -m "commit message"
$ git push origin 0.1.0-build-refactor
```

http://git-scm.com/book/en/Git-Branching-Basic-Branching-and-Merging

Oh, and as for the `.bash_profile` you probably don't have it. Just make the file

```
$ touch ~/.bash_profile
```

**Comment by johnmdonahue** [comment]
THIS LOOKS AMAZING!! Awesome work @sebnitu :thumbsup:

**Comment by sebnitu** [comment]
Thanks John :D

Awesome, that all makes sense. Thanks for that Oscar, will definitely be a lot easier next time I play with the styles :)

**Pull request merged**
