### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Kryptonit3-zz**
Missing .load() on one line

### CODE REVIEW

**Comment by OscarGodson** [comment]
I think that's in the Constructor docs, right? Not the quick start or load docs? I'm on mobile so cant see the full thing.

**Comment by Kryptonit3-zz** [comment]
When i copied from that box that had the options so I could edit along with the editor initiator I couldn't figure out why it wasn't rendering. Then I looked through the other documentation and saw it was missing the .load()

Idk, just thought I'd point it out. Feel free to disregard :)

**Comment by OscarGodson** [comment]
Someone else was confused by this as well. Thanks! I'll merge it, but can you run `jake docs` so it'll update the HTML docs?

**Comment by Kryptonit3-zz** [comment]
Ill be honest, I have no idea what that means. I am using the website. I saw it added a fork to my repos and I didn't know why, so I deleted it. You may have to fix it when you have time because I deleted the repo.

**Comment by OscarGodson** [comment]
Ah, there's a contributing guide which has the steps. Basically, install Jake (npm install -g jake) them run npm install then call jake docs and that's it.

**Comment by Kryptonit3-zz** [comment]
I am on Windows, I am sure there is a method for it on Windows. I will have to read up on proper contribution. :)

**Comment by OscarGodson** [comment]
All that should work totally fine on Windows :) Node and Jake both support Windows AFAIK

**Pull request closed without merging**
