### PR TITLE
Branch 0.1.0

### PR DESCRIPTION
**Pull request by johnmdonahue**
RE: [#44](https://github.com/OscarGodson/EpicEditor/pull/44#issuecomment-4384284)

I decided to name what was previously called `element`, `container` to try to be more clear on it's purpose. Hope that makes sense to you guys.

Also, I made an optional tweak to the `files` and `shortcuts` options. Singular seemed more consistent with an instance, similar to the `file` option. If you're not down with this feel free to disregard the last 2 commits in this pull request.
### A few additional notes/questions:
1. I'd love to be able to move away from updating `index.html` and `README` since they are nearly identical. Is this something we can throw in the `Jakefile` - to create the `index` on build?
2. Should file.name be checked to ensure it's a valid localStorage name - whatever that is?
3. Should the EE ID be protected (i.e. made not overwritable)?
### TODO:
- Bump version and disclaimer in docs however you see fit.

### CODE REVIEW

**Comment by OscarGodson** [comment]
The main issue is linking and having to change some wording and formatting. index.html isn't actually a direct port of README. I might be able take the generated HTML from the README and screw with the CSS tho to make it look ok.

file.name can be any string. AFAIK there's no issue with file names in LS. I should look into that tho.

Probably. Do you see any serious issues with it now being customizable?

Otherwise, looks awesome! ill clone, test, and get it into my the 0.1.0 branch on my side.

**Comment by johnmdonahue** [comment]
I started to fix the EE ID as discussed and ended up with more fixes. Apologies for the git bombs. I realize my pull requests have probably been a bit overambitious so let me know if you'd like commits/requests to be more incremental. :)

As a personal sanity check I created a "Try It" link on the index page and figured it might add to the content. In doing this I discovered a callback bug in the `unload` api and fixed that using the same code as `load`, so that commit is here as well.

Please feel free to cherry pick here. I just wanted to throw out some code before I take off for the weekend.

Thanks!

_Additional note_: It looks like `settings.id` is currently only being used to set a unique iframe id per instance. Maybe it would make sense to move this off of the settings since I can't imagine a purpose for it to be configurable - i.e `this.instanceId` or `this.iframeId`. The API already exposes getters for the element.

**Comment by OscarGodson** [comment]
It's all looking good. Just reading through all the code :) a lot core change stuff, but it's great.

I agree about id moving off settings. There's no reason for that.

P.S. the try it link is rad. great idea. I gotta make it more of a button so it stands out more too.

**Comment by OscarGodson** [comment]
Merged it in along with some more changes i made to other parts of the code. I didn't change any of your code so far, it looks great and works fine. I'll spend more time this weekend on it tho. Thanks again!

**Comment by johnmdonahue** [comment]
Hey, sorry for the late reply and thanks for the merge. I was looking back at the update to singularize `themes` and `shortcuts` and am now reconsidering if it makes sense.

Considering `editorInstance.settings.themes` (plural) makes sense in comparison to how I _was_ thinking of it as `editorInstance.theme`. Either way works I think, just wanted to throw that out there - that I'm not in any way married to that commit.

I'm back and available to jump on whatever you guys need and I'll do my best to shoot for less ambitious commits :) so just let me know if/where I can plug in (foounit, Jakefile etc).

Thanks again.

**Comment by OscarGodson** [comment]
Sweet! I just pushed a WIP 0.1.0 commit on my end. I removed the entire fullscreen API stuff since it only works in WebKit anyways and instead check if it's webkit or not and if not I do a homebrew fullscreen. I also did some other misc. fixes and updates. Feel free to merge my WIP if you want or you can wait, but thought i'd let you know.

And, for the pluralization, i think it makes sense making it singular as you'd probably do reference the themes and shortcuts like `ee.theme.preview` or `ee.shortcut.fullscreen`. I think it makes sense that way.

Just a warning, if you do pull in my WIP, remember, it's a WIP :) the code is a little jumbled in the fullscreen department as i've been trying to rip it all apart and put it back together by reusing as much as i can for the native and shim fullscreen. Oh, and you can't close fullscreen yet...

As for things to work on, tests would be very, very cool to have for the beta. Jake would be cool too, but I personally think Jake is less important than the tests since I would rather this run properly first. But it's a pull request and I'm pretty much happy to get anything :)

I gotta make you a core contributor here soon with these kinds of commits ;)

**Comment by johnmdonahue** [comment]
Sounds good. I'll play around with foounit some this week. It'd be great to get a basic JSHint config set up to just get that out of the way before going too heavy on the tests - less code to reconfigure down the line when we start linting. That said, if you get a chance to check out the config used [here (#44)](https://github.com/OscarGodson/EpicEditor/pull/44) and provide feedback that would be awesome.

Thanks.

**Comment by OscarGodson** [comment]
Will do! Main issue is `,` on new lines. I think you set that to be OK tho. I also commented on the commit for ya!

**Pull request merged**
