### PR TITLE
making UI strings configurable / providing alternative icons

### PR DESCRIPTION
**Pull request by cmtt**
This could be useful for i18n purposes.

### CODE REVIEW

**Comment by OscarGodson** [comment]
Great idea! Anyway you can submit this without all the whitespace changes? :)

**Comment by cmtt** [comment]
In addition, this pull request includes now alternative hand-drawn icons.

**Comment by OscarGodson** [comment]
Hey @cmtt - I want you to be able to be listed as a contributor on the https://github.com/OscarGodson/EpicEditor/graphs/contributors page, but right now there's a bunch of other commits. The sketch icons are nice but those would be part of a theme or something, not the core plus I dont want this package to grow too large. If you want to be listed there could you post a new pull request with just your UI string commit and without the whitespace changes? 

If you don't care I'll just make the change.

**Comment by cmtt** [comment]
This is surely reasonable, I should have had committed the icons in a seperate pull request. 
Eventually, the original changes are re-submitted in #199 .

**Pull request closed without merging**
